{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "from autogluon.tabular import TabularDataset, TabularPredictor\n",
    "train_data = TabularDataset('./train_sample.csv')\n",
    "test_data = TabularDataset('./test_sample.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "label = 'target'\n",
    "eval_metric = 'log_loss'\n",
    "time_limit = 1800"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "No path specified. Models will be saved in: \"AutogluonModels/ag-20220410_172209/\"\n",
      "Presets specified: ['best_quality']\n",
      "Beginning AutoGluon training ... Time limit = 1800s\n",
      "AutoGluon will save models to \"AutogluonModels/ag-20220410_172209/\"\n",
      "AutoGluon Version:  0.4.0\n",
      "Python Version:     3.8.10\n",
      "Operating System:   Linux\n",
      "Train Data Rows:    41245\n",
      "Train Data Columns: 93\n",
      "Label Column: target\n",
      "Preprocessing data ...\n",
      "AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == int, but few unique label-values observed).\n",
      "\t9 unique label values:  [7, 4, 2, 0, 5, 1, 8, 3, 6]\n",
      "\tIf 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])\n",
      "Train Data Class Count: 9\n",
      "Using Feature Generators to preprocess the data ...\n",
      "Dropping user-specified ignored columns: ['id']\n",
      "Fitting AutoMLPipelineFeatureGenerator...\n",
      "\tAvailable Memory:                    4254.17 MB\n",
      "\tTrain Data (Original)  Memory Usage: 30.69 MB (0.7% of available memory)\n",
      "\tInferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.\n",
      "\tStage 1 Generators:\n",
      "\t\tFitting AsTypeFeatureGenerator...\n",
      "\tStage 2 Generators:\n",
      "\t\tFitting FillNaFeatureGenerator...\n",
      "\tStage 3 Generators:\n",
      "\t\tFitting IdentityFeatureGenerator...\n",
      "\tStage 4 Generators:\n",
      "\t\tFitting DropUniqueFeatureGenerator...\n",
      "\tTypes of features in original data (raw dtype, special dtypes):\n",
      "\t\t('int', []) : 93 | ['feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5', ...]\n",
      "\tTypes of features in processed data (raw dtype, special dtypes):\n",
      "\t\t('int', []) : 93 | ['feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5', ...]\n",
      "\t0.2s = Fit runtime\n",
      "\t93 features in original data used to generate 93 features in processed data.\n",
      "\tTrain Data (Processed) Memory Usage: 30.69 MB (0.7% of available memory)\n",
      "Data preprocessing and feature engineering runtime = 0.7s ...\n",
      "AutoGluon will gauge predictive performance using evaluation metric: 'log_loss'\n",
      "\tThis metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()\n",
      "\tTo change this, specify the eval_metric parameter of Predictor()\n",
      "AutoGluon will fit 2 stack levels (L1 to L2) ...\n",
      "Fitting 13 L1 models ...\n",
      "Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 1199.23s of the 1799.29s of remaining time.\n",
      "Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)\n",
      "Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)\n",
      "\t-1.4314\t = Validation score   (log_loss)\n",
      "\t2.32s\t = Training   runtime\n",
      "\t1.46s\t = Validation runtime\n",
      "Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 1195.27s of the 1795.33s of remaining time.\n",
      "Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)\n",
      "Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)\n",
      "\t-1.4265\t = Validation score   (log_loss)\n",
      "\t0.11s\t = Training   runtime\n",
      "\t1.45s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 1193.6s of the 1793.66s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused NeuralNetFastAI_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=160492, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1074, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1032, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 577, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 153, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 211, in _fit\n",
      "    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 481, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 455, in after_all_folds_scheduled\n",
      "    raise processed_exception\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 423, in after_all_folds_scheduled\n",
      "    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError: \u001b[36mray::_ray_fit()\u001b[39m (pid=160492, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1170.43s of the 1770.49s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBMXT_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=160766, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1074, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1032, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 577, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 153, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 211, in _fit\n",
      "    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 481, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 455, in after_all_folds_scheduled\n",
      "    raise processed_exception\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 423, in after_all_folds_scheduled\n",
      "    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError: \u001b[36mray::_ray_fit()\u001b[39m (pid=160766, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Fitting model: LightGBM_BAG_L1 ... Training model for up to 1165.93s of the 1765.99s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBM_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=161039, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1074, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1032, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 577, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 153, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 211, in _fit\n",
      "    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 481, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 455, in after_all_folds_scheduled\n",
      "    raise processed_exception\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 423, in after_all_folds_scheduled\n",
      "    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError: \u001b[36mray::_ray_fit()\u001b[39m (pid=161039, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 1161.5s of the 1761.57s of remaining time.\n",
      "\tWarning: Reducing model 'n_estimators' from 300 -> 280 due to low memory. Expected memory usage reduced from 16.03% -> 15.0% of available memory...\n",
      "\t-0.6346\t = Validation score   (log_loss)\n",
      "\t8.05s\t = Training   runtime\n",
      "\t2.91s\t = Validation runtime\n",
      "Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 1148.03s of the 1748.09s of remaining time.\n",
      "\tWarning: Reducing model 'n_estimators' from 300 -> 264 due to low memory. Expected memory usage reduced from 17.01% -> 15.0% of available memory...\n",
      "\t-0.6517\t = Validation score   (log_loss)\n",
      "\t6.94s\t = Training   runtime\n",
      "\t2.77s\t = Validation runtime\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 1133.26s of the 1733.32s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused CatBoost_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=161386, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1074, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1032, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 577, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 153, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 211, in _fit\n",
      "    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 481, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 455, in after_all_folds_scheduled\n",
      "    raise processed_exception\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 423, in after_all_folds_scheduled\n",
      "    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError: \u001b[36mray::_ray_fit()\u001b[39m (pid=161386, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 1128.81s of the 1728.87s of remaining time.\n",
      "\tWarning: Reducing model 'n_estimators' from 300 -> 210 due to low memory. Expected memory usage reduced from 21.37% -> 15.0% of available memory...\n",
      "\t-0.6907\t = Validation score   (log_loss)\n",
      "\t5.77s\t = Training   runtime\n",
      "\t2.26s\t = Validation runtime\n",
      "Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 1117.91s of the 1717.97s of remaining time.\n",
      "\tWarning: Reducing model 'n_estimators' from 300 -> 202 due to low memory. Expected memory usage reduced from 22.23% -> 15.0% of available memory...\n",
      "\t-0.7164\t = Validation score   (log_loss)\n",
      "\t5.16s\t = Training   runtime\n",
      "\t2.2s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L1 ... Training model for up to 1104.94s of the 1705.0s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused XGBoost_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=161733, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1074, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1032, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 577, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 153, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 211, in _fit\n",
      "    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 481, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 455, in after_all_folds_scheduled\n",
      "    raise processed_exception\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 423, in after_all_folds_scheduled\n",
      "    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError: \u001b[36mray::_ray_fit()\u001b[39m (pid=161733, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 1088.17s of the 1688.24s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused NeuralNetTorch_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=162006, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1074, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1032, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 577, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 153, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 211, in _fit\n",
      "    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 481, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 455, in after_all_folds_scheduled\n",
      "    raise processed_exception\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 423, in after_all_folds_scheduled\n",
      "    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError: \u001b[36mray::_ray_fit()\u001b[39m (pid=162006, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1083.58s of the 1683.64s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBMLarge_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=162291, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1074, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1032, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 577, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 153, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 211, in _fit\n",
      "    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 481, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 455, in after_all_folds_scheduled\n",
      "    raise processed_exception\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 423, in after_all_folds_scheduled\n",
      "    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError: \u001b[36mray::_ray_fit()\u001b[39m (pid=162291, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Repeating k-fold bagging: 2/20\n",
      "Repeating k-fold bagging: 3/20\n",
      "Repeating k-fold bagging: 4/20\n",
      "Repeating k-fold bagging: 5/20\n",
      "Repeating k-fold bagging: 6/20\n",
      "Repeating k-fold bagging: 7/20\n",
      "Repeating k-fold bagging: 8/20\n",
      "Repeating k-fold bagging: 9/20\n",
      "Repeating k-fold bagging: 10/20\n",
      "Repeating k-fold bagging: 11/20\n",
      "Repeating k-fold bagging: 12/20\n",
      "Repeating k-fold bagging: 13/20\n",
      "Repeating k-fold bagging: 14/20\n",
      "Repeating k-fold bagging: 15/20\n",
      "Repeating k-fold bagging: 16/20\n",
      "Repeating k-fold bagging: 17/20\n",
      "Repeating k-fold bagging: 18/20\n",
      "Repeating k-fold bagging: 19/20\n",
      "Repeating k-fold bagging: 20/20\n",
      "Completed 20/20 k-fold bagging repeats ...\n",
      "Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 1678.78s of remaining time.\n",
      "\t-0.5708\t = Validation score   (log_loss)\n",
      "\t9.78s\t = Training   runtime\n",
      "\t0.01s\t = Validation runtime\n",
      "Fitting 11 L2 models ...\n",
      "Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 1668.93s of the 1668.88s of remaining time.\n",
      "\tMemory not enough to fit NNFastAiTabularModel folds in parallel. Will do sequential fitting instead. \tConsider decreasing folds trained in parallel by passing num_folds_parallel to ag_args_ensemble when calling predictor.fit\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy\n",
      "No improvement since epoch 9: early stopping\n",
      "No improvement since epoch 8: early stopping\n",
      "No improvement since epoch 9: early stopping\n",
      "No improvement since epoch 7: early stopping\n",
      "No improvement since epoch 7: early stopping\n",
      "\t-0.4846\t = Validation score   (log_loss)\n",
      "\t249.52s\t = Training   runtime\n",
      "\t1.79s\t = Validation runtime\n",
      "Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 1417.16s of the 1417.12s of remaining time.\n",
      "\tMemory not enough to fit LGBModel folds in parallel. Will do sequential fitting instead. \tConsider decreasing folds trained in parallel by passing num_folds_parallel to ag_args_ensemble when calling predictor.fit\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy\n",
      "\t-0.4747\t = Validation score   (log_loss)\n",
      "\t85.48s\t = Training   runtime\n",
      "\t0.74s\t = Validation runtime\n",
      "Fitting model: LightGBM_BAG_L2 ... Training model for up to 1330.22s of the 1330.18s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBM_BAG_L2 to fail during training... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=162807, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1074, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1032, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 577, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 153, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 211, in _fit\n",
      "    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 481, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 455, in after_all_folds_scheduled\n",
      "    raise processed_exception\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 423, in after_all_folds_scheduled\n",
      "    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError: \u001b[36mray::_ray_fit()\u001b[39m (pid=162807, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Fitting model: RandomForestGini_BAG_L2 ... Training model for up to 1325.73s of the 1325.67s of remaining time.\n",
      "\t-0.5419\t = Validation score   (log_loss)\n",
      "\t10.91s\t = Training   runtime\n",
      "\t3.53s\t = Validation runtime\n",
      "Fitting model: RandomForestEntr_BAG_L2 ... Training model for up to 1310.77s of the 1310.73s of remaining time.\n",
      "\t-0.5321\t = Validation score   (log_loss)\n",
      "\t11.09s\t = Training   runtime\n",
      "\t3.48s\t = Validation runtime\n",
      "Fitting model: CatBoost_BAG_L2 ... Training model for up to 1295.76s of the 1295.72s of remaining time.\n",
      "\tMemory not enough to fit CatBoostModel folds in parallel. Will do sequential fitting instead. \tConsider decreasing folds trained in parallel by passing num_folds_parallel to ag_args_ensemble when calling predictor.fit\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy\n",
      "\tRan out of time, early stopping on iteration 1524.\n",
      "\tRan out of time, early stopping on iteration 1632.\n",
      "\tRan out of time, early stopping on iteration 1711.\n",
      "\tRan out of time, early stopping on iteration 1920.\n",
      "\t-0.4753\t = Validation score   (log_loss)\n",
      "\t1192.93s\t = Training   runtime\n",
      "\t0.31s\t = Validation runtime\n",
      "Fitting model: ExtraTreesGini_BAG_L2 ... Training model for up to 102.18s of the 102.14s of remaining time.\n",
      "\t-0.5405\t = Validation score   (log_loss)\n",
      "\t7.36s\t = Training   runtime\n",
      "\t3.63s\t = Validation runtime\n",
      "Fitting model: ExtraTreesEntr_BAG_L2 ... Training model for up to 89.64s of the 89.59s of remaining time.\n",
      "\t-0.535\t = Validation score   (log_loss)\n",
      "\t6.88s\t = Training   runtime\n",
      "\t3.61s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L2 ... Training model for up to 77.77s of the 77.71s of remaining time.\n",
      "\tMemory not enough to fit XGBoostModel folds in parallel. Will do sequential fitting instead. \tConsider decreasing folds trained in parallel by passing num_folds_parallel to ag_args_ensemble when calling predictor.fit\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy\n",
      "\t-0.4782\t = Validation score   (log_loss)\n",
      "\t74.49s\t = Training   runtime\n",
      "\t0.66s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 2.13s of the 2.08s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused NeuralNetTorch_BAG_L2 to fail during training... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=163738, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1074, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1032, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 577, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 153, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 211, in _fit\n",
      "    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 481, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 455, in after_all_folds_scheduled\n",
      "    raise processed_exception\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 423, in after_all_folds_scheduled\n",
      "    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError: \u001b[36mray::_ray_fit()\u001b[39m (pid=163738, ip=192.168.1.7)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 268, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 191, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 169, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band, buffers=buffers)\n",
      "AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/vladimir/Downloads/ilykey/Assignment 5 SVM/env/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Completed 1/20 k-fold bagging repeats ...\n",
      "Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.0s of the -5.07s of remaining time.\n",
      "\t-0.4642\t = Validation score   (log_loss)\n",
      "\t11.75s\t = Training   runtime\n",
      "\t0.01s\t = Validation runtime\n",
      "AutoGluon training complete, total runtime = 1816.91s ... Best model: \"WeightedEnsemble_L3\"\n",
      "TabularPredictor saved. To load, use: predictor = TabularPredictor.load(\"AutogluonModels/ag-20220410_172209/\")\n"
     ]
    }
   ],
   "source": [
    "predictor = TabularPredictor(\n",
    "    label=label, eval_metric=eval_metric, learner_kwargs={'ignored_columns': ['id']}\n",
    ").fit(train_data, presets='best_quality', time_limit=time_limit)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>model</th>\n",
       "      <th>score_val</th>\n",
       "      <th>pred_time_val</th>\n",
       "      <th>fit_time</th>\n",
       "      <th>pred_time_val_marginal</th>\n",
       "      <th>fit_time_marginal</th>\n",
       "      <th>stack_level</th>\n",
       "      <th>can_infer</th>\n",
       "      <th>fit_order</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>WeightedEnsemble_L3</td>\n",
       "      <td>-0.464190</td>\n",
       "      <td>23.651973</td>\n",
       "      <td>1660.503248</td>\n",
       "      <td>0.009509</td>\n",
       "      <td>11.751428</td>\n",
       "      <td>3</td>\n",
       "      <td>True</td>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>LightGBMXT_BAG_L2</td>\n",
       "      <td>-0.474732</td>\n",
       "      <td>13.794194</td>\n",
       "      <td>113.837572</td>\n",
       "      <td>0.741396</td>\n",
       "      <td>85.479125</td>\n",
       "      <td>2</td>\n",
       "      <td>True</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>CatBoost_BAG_L2</td>\n",
       "      <td>-0.475320</td>\n",
       "      <td>13.360329</td>\n",
       "      <td>1221.291157</td>\n",
       "      <td>0.307531</td>\n",
       "      <td>1192.932709</td>\n",
       "      <td>2</td>\n",
       "      <td>True</td>\n",
       "      <td>12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>XGBoost_BAG_L2</td>\n",
       "      <td>-0.478229</td>\n",
       "      <td>13.714705</td>\n",
       "      <td>102.851184</td>\n",
       "      <td>0.661907</td>\n",
       "      <td>74.492737</td>\n",
       "      <td>2</td>\n",
       "      <td>True</td>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>NeuralNetFastAI_BAG_L2</td>\n",
       "      <td>-0.484552</td>\n",
       "      <td>14.841750</td>\n",
       "      <td>277.878436</td>\n",
       "      <td>1.788952</td>\n",
       "      <td>249.519989</td>\n",
       "      <td>2</td>\n",
       "      <td>True</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>RandomForestEntr_BAG_L2</td>\n",
       "      <td>-0.532090</td>\n",
       "      <td>16.530161</td>\n",
       "      <td>39.444202</td>\n",
       "      <td>3.477363</td>\n",
       "      <td>11.085755</td>\n",
       "      <td>2</td>\n",
       "      <td>True</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>ExtraTreesEntr_BAG_L2</td>\n",
       "      <td>-0.535002</td>\n",
       "      <td>16.665314</td>\n",
       "      <td>35.241505</td>\n",
       "      <td>3.612516</td>\n",
       "      <td>6.883058</td>\n",
       "      <td>2</td>\n",
       "      <td>True</td>\n",
       "      <td>14</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>ExtraTreesGini_BAG_L2</td>\n",
       "      <td>-0.540463</td>\n",
       "      <td>16.677840</td>\n",
       "      <td>35.722249</td>\n",
       "      <td>3.625042</td>\n",
       "      <td>7.363802</td>\n",
       "      <td>2</td>\n",
       "      <td>True</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>RandomForestGini_BAG_L2</td>\n",
       "      <td>-0.541873</td>\n",
       "      <td>16.586180</td>\n",
       "      <td>39.270308</td>\n",
       "      <td>3.533382</td>\n",
       "      <td>10.911860</td>\n",
       "      <td>2</td>\n",
       "      <td>True</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>WeightedEnsemble_L2</td>\n",
       "      <td>-0.570829</td>\n",
       "      <td>11.599061</td>\n",
       "      <td>35.816963</td>\n",
       "      <td>0.011022</td>\n",
       "      <td>9.779547</td>\n",
       "      <td>2</td>\n",
       "      <td>True</td>\n",
       "      <td>7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>RandomForestGini_BAG_L1</td>\n",
       "      <td>-0.634610</td>\n",
       "      <td>2.905268</td>\n",
       "      <td>8.048025</td>\n",
       "      <td>2.905268</td>\n",
       "      <td>8.048025</td>\n",
       "      <td>1</td>\n",
       "      <td>True</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>RandomForestEntr_BAG_L1</td>\n",
       "      <td>-0.651703</td>\n",
       "      <td>2.770288</td>\n",
       "      <td>6.943668</td>\n",
       "      <td>2.770288</td>\n",
       "      <td>6.943668</td>\n",
       "      <td>1</td>\n",
       "      <td>True</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>ExtraTreesGini_BAG_L1</td>\n",
       "      <td>-0.690710</td>\n",
       "      <td>2.260257</td>\n",
       "      <td>5.774871</td>\n",
       "      <td>2.260257</td>\n",
       "      <td>5.774871</td>\n",
       "      <td>1</td>\n",
       "      <td>True</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>ExtraTreesEntr_BAG_L1</td>\n",
       "      <td>-0.716408</td>\n",
       "      <td>2.200207</td>\n",
       "      <td>5.163677</td>\n",
       "      <td>2.200207</td>\n",
       "      <td>5.163677</td>\n",
       "      <td>1</td>\n",
       "      <td>True</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>KNeighborsDist_BAG_L1</td>\n",
       "      <td>-1.426484</td>\n",
       "      <td>1.452020</td>\n",
       "      <td>0.107175</td>\n",
       "      <td>1.452020</td>\n",
       "      <td>0.107175</td>\n",
       "      <td>1</td>\n",
       "      <td>True</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>KNeighborsUnif_BAG_L1</td>\n",
       "      <td>-1.431415</td>\n",
       "      <td>1.464759</td>\n",
       "      <td>2.321032</td>\n",
       "      <td>1.464759</td>\n",
       "      <td>2.321032</td>\n",
       "      <td>1</td>\n",
       "      <td>True</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                      model  score_val  pred_time_val     fit_time  \\\n",
       "0       WeightedEnsemble_L3  -0.464190      23.651973  1660.503248   \n",
       "1         LightGBMXT_BAG_L2  -0.474732      13.794194   113.837572   \n",
       "2           CatBoost_BAG_L2  -0.475320      13.360329  1221.291157   \n",
       "3            XGBoost_BAG_L2  -0.478229      13.714705   102.851184   \n",
       "4    NeuralNetFastAI_BAG_L2  -0.484552      14.841750   277.878436   \n",
       "5   RandomForestEntr_BAG_L2  -0.532090      16.530161    39.444202   \n",
       "6     ExtraTreesEntr_BAG_L2  -0.535002      16.665314    35.241505   \n",
       "7     ExtraTreesGini_BAG_L2  -0.540463      16.677840    35.722249   \n",
       "8   RandomForestGini_BAG_L2  -0.541873      16.586180    39.270308   \n",
       "9       WeightedEnsemble_L2  -0.570829      11.599061    35.816963   \n",
       "10  RandomForestGini_BAG_L1  -0.634610       2.905268     8.048025   \n",
       "11  RandomForestEntr_BAG_L1  -0.651703       2.770288     6.943668   \n",
       "12    ExtraTreesGini_BAG_L1  -0.690710       2.260257     5.774871   \n",
       "13    ExtraTreesEntr_BAG_L1  -0.716408       2.200207     5.163677   \n",
       "14    KNeighborsDist_BAG_L1  -1.426484       1.452020     0.107175   \n",
       "15    KNeighborsUnif_BAG_L1  -1.431415       1.464759     2.321032   \n",
       "\n",
       "    pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \\\n",
       "0                 0.009509          11.751428            3       True   \n",
       "1                 0.741396          85.479125            2       True   \n",
       "2                 0.307531        1192.932709            2       True   \n",
       "3                 0.661907          74.492737            2       True   \n",
       "4                 1.788952         249.519989            2       True   \n",
       "5                 3.477363          11.085755            2       True   \n",
       "6                 3.612516           6.883058            2       True   \n",
       "7                 3.625042           7.363802            2       True   \n",
       "8                 3.533382          10.911860            2       True   \n",
       "9                 0.011022           9.779547            2       True   \n",
       "10                2.905268           8.048025            1       True   \n",
       "11                2.770288           6.943668            1       True   \n",
       "12                2.260257           5.774871            1       True   \n",
       "13                2.200207           5.163677            1       True   \n",
       "14                1.452020           0.107175            1       True   \n",
       "15                1.464759           2.321032            1       True   \n",
       "\n",
       "    fit_order  \n",
       "0          16  \n",
       "1           9  \n",
       "2          12  \n",
       "3          15  \n",
       "4           8  \n",
       "5          11  \n",
       "6          14  \n",
       "7          13  \n",
       "8          10  \n",
       "9           7  \n",
       "10          3  \n",
       "11          4  \n",
       "12          5  \n",
       "13          6  \n",
       "14          2  \n",
       "15          1  "
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "predictor.leaderboard(silent=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "      <th>3</th>\n",
       "      <th>4</th>\n",
       "      <th>5</th>\n",
       "      <th>6</th>\n",
       "      <th>7</th>\n",
       "      <th>8</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>0.000473</td>\n",
       "      <td>0.785458</td>\n",
       "      <td>0.156590</td>\n",
       "      <td>0.045958</td>\n",
       "      <td>0.000385</td>\n",
       "      <td>0.000550</td>\n",
       "      <td>0.009251</td>\n",
       "      <td>0.000722</td>\n",
       "      <td>0.000613</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>0.001260</td>\n",
       "      <td>0.135894</td>\n",
       "      <td>0.206742</td>\n",
       "      <td>0.013261</td>\n",
       "      <td>0.000163</td>\n",
       "      <td>0.008762</td>\n",
       "      <td>0.617998</td>\n",
       "      <td>0.015461</td>\n",
       "      <td>0.000459</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>0.000224</td>\n",
       "      <td>0.684390</td>\n",
       "      <td>0.271769</td>\n",
       "      <td>0.040924</td>\n",
       "      <td>0.000154</td>\n",
       "      <td>0.000243</td>\n",
       "      <td>0.001799</td>\n",
       "      <td>0.000271</td>\n",
       "      <td>0.000227</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>0.258510</td>\n",
       "      <td>0.003800</td>\n",
       "      <td>0.001721</td>\n",
       "      <td>0.000547</td>\n",
       "      <td>0.000945</td>\n",
       "      <td>0.020167</td>\n",
       "      <td>0.014728</td>\n",
       "      <td>0.013016</td>\n",
       "      <td>0.686566</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>0.000521</td>\n",
       "      <td>0.592581</td>\n",
       "      <td>0.371535</td>\n",
       "      <td>0.029200</td>\n",
       "      <td>0.000181</td>\n",
       "      <td>0.000370</td>\n",
       "      <td>0.004403</td>\n",
       "      <td>0.000526</td>\n",
       "      <td>0.000683</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   id         0         1         2         3         4         5         6  \\\n",
       "0   1  0.000473  0.785458  0.156590  0.045958  0.000385  0.000550  0.009251   \n",
       "1   2  0.001260  0.135894  0.206742  0.013261  0.000163  0.008762  0.617998   \n",
       "2   3  0.000224  0.684390  0.271769  0.040924  0.000154  0.000243  0.001799   \n",
       "3   4  0.258510  0.003800  0.001721  0.000547  0.000945  0.020167  0.014728   \n",
       "4   5  0.000521  0.592581  0.371535  0.029200  0.000181  0.000370  0.004403   \n",
       "\n",
       "          7         8  \n",
       "0  0.000722  0.000613  \n",
       "1  0.015461  0.000459  \n",
       "2  0.000271  0.000227  \n",
       "3  0.013016  0.686566  \n",
       "4  0.000526  0.000683  "
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "submission = test_data[['id']]\n",
    "test_pred_proba = predictor.predict_proba(test_data)\n",
    "submission = pd.concat([submission, test_pred_proba], axis=1)\n",
    "submission.to_csv('result.csv', index=False)\n",
    "submission.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
